---
bolt_postgres_database: bolt
bolt_postgres_user: bolt
bolt_postgres_host: localhost
bolt_postgres_password: "{{ lookup('password', 'secrets/' + ansible_nodename + '/postgres/users/' + bolt_postgres_user + '/password') }}"

bolt_postgres_pool_size: 2

bolt_repository_url: https://github.com/jchristgit/bolt
# git reference
bolt_version: master
bolt_release_version: 0.11.2
bolt_checkout_directory: /usr/local/src/bolt

bolt_cookie: "{{ lookup('password', 'secrets/' + ansible_nodename + '/bolt/erlang.cookie') }}"
bolt_service_user: bolt
bolt_directory: /opt/bolt

bolt_pgsql_url: ecto://{{ bolt_postgres_user }}:{{ bolt_postgres_password }}@{{ bolt_postgres_host }}/{{ bolt_postgres_database }}?pool_size={{ bolt_postgres_pool_size }}

# vim: sw=2 ts=2:
