sudo: enabled
language: elixir
elixir: 1.9.4

jobs:
  include:
  - stage: check
    script:
    - mix format --check-formatted
    - mix credo --strict
  - stage: test
    services:
      - postgresql
    addons:
      postgresql: "9.6"
    before_install:
    - sudo service postgresql stop
    - sudo apt-get remove -q 'postgresql-*'
    - sudo apt update -q
    - sudo apt install postgresql-10 postgresql-client-10
    - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
    - sudo service postgresql restart
    before_script:
    - sudo -u postgres psql -c "CREATE USER travis PASSWORD 'travis' SUPERUSER;" -h localhost
    - psql -c 'CREATE USER bolt;' -h localhost -d postgres
    - psql -c 'CREATE DATABASE bolt_test OWNER bolt;' -h localhost -d postgres
    script:
    - mix test --no-start
    env:
      MIX_ENV: test
      PGSQL_TEST_URL: postgres://bolt:@127.0.0.1/bolt_test
      PGHOST: localhost
      PGPORT: 5432
