sudo: enabled
language: elixir
elixir: 1.7.2

jobs:
  include:
  - stage: check
    script:
    - mix format --check-formatted
    - mix credo --strict
  - stage: test
    services:
      - postgresql
    addons:
      postgresql: "9.6"
    before_install:
    - sudo service postgresql stop
    - sudo apt-get remove -q 'postgresql-*'
    - sudo apt update -q
    - sudo apt install postgresql-10 postgresql-client-10
    - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
    - sudo service postgresql restart
    before_script:
    - sudo -u postgres psql -c "CREATE USER travis PASSWORD 'travis' SUPERUSER;" -h localhost
    - psql -c 'CREATE USER bolt;' -h localhost -d postgres
    - psql -c 'CREATE DATABASE bolt_test OWNER bolt;' -h localhost -d postgres
    script:
    - mix ecto.create
    - mix ecto.migrate
    - mix test --no-start
    env:
      PGSQL_TEST_URL: postgres://bolt:@127.0.0.1/bolt_test
  - stage: build
    if: branch = master
    script:
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - sudo docker build -t bolt .
    - sudo docker push $DOCKER_USERNAME/bolt

env:
  DOCKER_USERNAME:
    secure: H47nq3wVYuXJMtr0Bu7tV0yPpxuF+92aEA4GVgqby5AQL0YyUPau4AhYFSBd7Egs1VRDRlQzsX7NWCpjh6qYfFa53LJrXhYtbeiTYLLKgz0DbWSqCRNLeZ4W86vLVO1fDHkmjFVSczUk4lzBW4y4pn3zQdFXEAm5jPq0DXB4/O1ucfQ1oyNE6dyJMSWj1bBZuVoXkm+uaKdmdLB1qs7oSqJZ3VidRYfF/LItasX0br7sS3E/j6SHbPlzzrlzXvyOc0oRuksmS1bkMCdj+krStCF/idunoFxAERDLeiIvrTD8L8NDxHpYbXiIMAxYa4X2KmylHF907JQAup8Ekr511mw8PRpjRJzPRSDgHLFIZinoiXU7io7rVTChPnslsaSzJ2ToR+xmbk9RDWDIMtXBHl6JBYzUEyM5yYe1LPXUuRrU4ccNbzdzInsSLuMLi3TvmnIX1Ucx4bkphbFjQH5AJs51hPiuFMHBWXYdnb1AC6NC8nsgrI9lhduOHe4fhk1+l5IOEG/uOQQC8mpFn6mViOKCajWS32qLpNL07dUg0LdlFrXRIb9NKPyK1rWi14A1Iy9htKBhw0eN6Ykifr6fL430vHaprnxGdzEi2kCGh57n01otljs/HV495VeNe05sLeqyVGavsTf7jcayCYsB3HQNibVniEn4i8vMery3iYE=
  DOCKER_PASSWORD:
    secure: tzh26M8OtnP9W8tTrvEkT0lL1eb1MphYSrugCUOo8yCEBu49DHzYxnORpIA43iQ52c9qiPi5degSMyNc8zzhPbT89+ZDyCyuAuauYHfPAo/sF0gtvNXSsC66Qv8SOjoXfpFwJJGVYQTpWNbPGUHf9b2a02RDHd7lgEJwVeEnvFQS61J0J2R3rpCzDZx13QwoXxZLDZcCkGsqpUUsFn6Sk+6KGWSrGauPsu7xH3gSbT6LnBwFpsq9yx7W7DtQ9NT9QYXV6hfkBbhZi+ZgrcDYhSkCn8pEu4oVU51xE2fdXJrLGiDtLGjD7uy8RPf50l1NrKSr1EElDoSbs+PNuvXOweuiTrTCZISmmRlOIZc13tifGiRBZzAptaFB/ChfOoRS3x7Gj8xq0VabhaAUP8a7A91He18bxhLA9oHNGh6NsqHN5SycQAF7f6gkT7SiljBMQpwvOTDJE3z3bDQAY4iWrLsAUGFFdwddYYLF4T+ozMlGfOyvI0rIvSEdBHsQkMMX1M8culX/TllEVBoO24WhhQBjvIkViouCjdBdhy+/sxEqh8IV3q5iivxI9UTx0g3cdXK/AFg5gxkgVvLsAB1jq3VjzmWiCDkREcQ0ozs+2sNqjvhEa8UnuUxk28mcKx6d4bHsBR1eMouwXwgv6FRhTlqjSX2tD1s3IpbPbdvdrqA=
  global:
    PGPORT: 5432
    PGHOST: localhost
