---
version: '3'
services:
  bolt:
    build: .
    image: jchristhub/bolt
    restart: unless-stopped
    command: docker/migrate_and_boot.sh
    depends_on:
      - postgres
    networks:
      - postgres
    environment:
      - BASE_DOC_URL
      - BOTLOG_CHANNEL
      - BOT_TOKEN
      - PGSQL_URL=ecto://bolt:$POSTGRES_PASSWORD@postgres/bolt?pool_size=1
      - SUPERUSERS
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 10

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=bolt
      - POSTGRES_USER=bolt
      - POSTGRES_PASSWORD
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  postgres:

volumes:
  postgres:

# vim: sw=2 ts=2:
