---
- name: ensure the `{{ bolt_postgres_user }}` postgres user exists
  become: yes
  become_user: postgres
  postgresql_user:
    name: bolt
    password: "{{ bolt_postgres_password }}"
    state: present
  tags:
    - postgres
  when: bolt_postgres_host in ansible_all_ipv4_addresses

- name: ensure the `{{ bolt_postgres_database }}` postgres database exists
  become: yes
  become_user: postgres
  postgresql_db:
    name: bolt
    owner: bolt
    state: present
  tags:
    - postgres
  when: bolt_postgres_host in ansible_all_ipv4_addresses

- name: ensure swarm containers can connect to postgresql
  include_role:
    name: postgres-swarm
    tasks_from: accept_from
  vars:
    swarm_clients:
      - { db: "{{ bolt_postgres_database }}", user: "{{ bolt_postgres_user }}" }
