---
- name: install https repository dependencies
  package:
    name:
      - ca-certificates
      - curl
    state: present
  tags:
    - packages
    - postgresql

- name: add the postgresql apt key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags:
    - apt
    - postgresql

- name: add the postgresql apt repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main
    state: present
  tags:
    - apt
    - postgresql

- name: install postgresql {{ postgresql_version }}
  apt:
    name: postgresql-{{ postgresql_version }}
    state: present
  tags:
    - packages
    - postgresql
