name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-slim
      
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: bolt
          POSTGRES_PASSWORD: bolt
          POSTGRES_DB: bolt
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Check code style
      run: mix credo --strict
    - name: Run Tests
      run: mix test --no-start
      env:
        PGSQL_URL: postgres://bolt:bolt@$postgres:${{ job.services.postgres.ports[5432] }}/bolt
